### ISSUE TITLE
[BUG] Black sky when choosing a team

### ISSUE THREAD

**Issue by crashzk** [samyycX/CS2-SkyboxChanger#2]
It wouldn't be a big bug, error. However, I noticed that whenever I connect to the server, during the time of choosing one of the teams the sky turns black, it only goes to the map pattern after I join one of the teams or choose to just watch.

I only tested with the map's default skyboxes at the moment.

**Comment by crashzk** [comment]
I changed the skybox, and even so, when I connect, it shows the black sky first, before choosing a team.

![image](https://github.com/user-attachments/assets/1535ff2d-8acb-4cf8-a570-ee77fe958df1)

**Comment by samyycX** [comment]
There's currently no good solution for this. Spawning skybox too early will cause 3d skybox spawn in wrong location randomly for some player.

**Comment by samyycX** [comment]
Check the v1.2.1 release, maybe it fix the problem

**Comment by crashzk** [comment]
I'm using the [latest version](https://github.com/samyycX/CS2-SkyboxChanger/releases/tag/release-v1.2.2), black sky when choosing a team seems to have resolved it, everything is fine now.

However, it shows this error log in the console:
```
2024-12-15 11:36:03.131 -03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SkyboxChanger.Service.GetPlayerSkybox(CCSPlayerController player) in E:\programming\CS2-SkyboxChanger\Service.cs:line 57
   at SkyboxChanger.SkyboxChanger.<Load>b__30_7() in E:\programming\CS2-SkyboxChanger\Plugin.cs:line 70
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```
